# -*- coding: utf-8 -*-
"""Taller #2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E463YdXBtbNPGdHbbLgA6sGDxeg3p_X6

Taller python #2

Hecho por Santiago Yucuma Rodriguez
"""

#Ejercicio 1, 2 y 3

def bienvenida(edad):
    if edad < 18:
        print("Lamento informarte que eres menor de edad. No puedes acceder al programa.")
        return

    def pedirEdad():
        if edad >= 18:
            print("Bienvenido al programa, eres mayor de edad.")
        else:
            print(f"Lamento informarte que eres menor de edad. No puedes acceder al programa. Te faltan {18 - edad} años.")

    pedirEdad()

    def generacionPertenece():
        if 24 < edad < 40:
            print("Perteneces a la generación millennial.")
        elif 10 < edad < 24:
            print("Perteneces a la Generación Z.")
        elif 0 < edad < 10:
            print("Perteneces a la Generación Alfa.")
        else:
            print("Eres un Boomer.")

    generacionPertenece()

    def numeroRedondo():
        if edad % 10 == 0:
            print("Tu edad es un número redondo.")
            return True
        else:
            print("Tu edad no es un número redondo.")
            return False

    numeroRedondo()

menBienvenida = input("Ingresa tu nombre, por favor: ")
print(f"Bienvenido al programa, {menBienvenida}.")

ingresesuEdad = int(input("Por favor, ingresa tu edad: "))
bienvenida(ingresesuEdad)

#Ejercicio 4

def agregar_contacto(agenda):
    nombre = input("Ingresa el nombre del contacto: ")
    telefono = input("Ingresa el teléfono del contacto: ")
    agenda[nombre] = telefono
    print(f"Contacto {nombre} agregado correctamente.")

def buscar_contacto(agenda):
    nombre = input("Ingresa el nombre del contacto que deseas buscar: ")
    if nombre in agenda:
        print(f"Teléfono de {nombre}: {agenda[nombre]}")
    else:
        print(f"{nombre} no está en la lista de contactos.")

def mostrar_contactos(agenda):
    print("Lista de contactos:")
    for nombre, telefono in agenda.items():
        print(f"{nombre}: {telefono}")

def editar_contacto(agenda):
    nombre = input("Ingresa el nombre del contacto que deseas editar: ")
    if nombre in agenda:
        nuevo_telefono = input("Ingresa el nuevo teléfono: ")
        agenda[nombre] = nuevo_telefono
        print(f"Teléfono de {nombre} actualizado correctamente.")
    else:
        print(f"{nombre} no está en la lista de contactos.")

def principal():
    agenda = {}

    while True:
        print("\n--- Agenda de Contactos ---")
        print("1. Agregar Contacto")
        print("2. Buscar Contacto")
        print("3. Mostrar Contactos")
        print("4. Editar Contacto")
        print("5. Salir")

        opcion = input("Elige una opción (1-5): ")

        if opcion == "1":
            agregar_contacto(agenda)
        elif opcion == "2":
            buscar_contacto(agenda)
        elif opcion == "3":
            mostrar_contactos(agenda)
        elif opcion == "4":
            editar_contacto(agenda)
        elif opcion == "5":
            print("¡Hasta luego!")
            break
        else:
            print("Opción inválida. Inténtalo de nuevo.")

if __name__ == "__main__":
    principal()

#Efercico 5

def agregar_invitado(lista_invitados):
    nombre = input("Ingresa el nombre del invitado: ")
    lista_invitados.append(nombre)
    print(f"{nombre} ha sido añadido a la lista de invitados.")

def eliminar_invitado(lista_invitados):
    nombre = input("Ingresa el nombre del invitado que deseas eliminar: ")
    if nombre in lista_invitados:
        lista_invitados.remove(nombre)
        print(f"{nombre} ha sido eliminado de la lista de invitados.")
    else:
        print(f"{nombre} no está en la lista de invitados.")

def verificar_invitado(lista_invitados):
    nombre = input("Ingresa el nombre del invitado que deseas verificar: ")
    if nombre in lista_invitados:
        print(f"{nombre} está en la lista de invitados.")
    else:
        print(f"{nombre} no está en la lista de invitados.")

def editar_invitado(lista_invitados):
    nombre_actual = input("Ingresa el nombre del invitado que deseas editar: ")
    if nombre_actual in lista_invitados:
        nuevo_nombre = input("Ingresa el nuevo nombre: ")
        lista_invitados[lista_invitados.index(nombre_actual)] = nuevo_nombre
        print(f"{nombre_actual} ha sido actualizado a {nuevo_nombre}.")
    else:
        print(f"{nombre_actual} no está en la lista de invitados.")

def funPadre():
    lista_invitados = []  # Creamos una lista vacía para almacenar los invitados

    while True:
        print("\n--- Gestión de Invitados ---")
        print("1. Agregar Invitado")
        print("2. Eliminar Invitado")
        print("3. Verificar Invitado")
        print("4. Editar Invitado")
        print("5. Salir")

        opcion = input("Elige una opción (1-5): ")

        if opcion == "1":
            agregar_invitado(lista_invitados)
        elif opcion == "2":
            eliminar_invitado(lista_invitados)
        elif opcion == "3":
            verificar_invitado(lista_invitados)
        elif opcion == "4":
            editar_invitado(lista_invitados)
        elif opcion == "5":
            print("¡Hasta luego!")
            break
        else:
            print("Opción inválida. Inténtalo de nuevo.")

if __name__ == "__main__":
    funPadre()